### ISSUE TITLE
Deprecated selector in `chrome-dark-syntax\index.less`

### ISSUE THREAD

**Issue by slaiyer** [puranjayjain/chrome-dark-syntax#2]
In `chrome-dark-syntax\index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor,
:host` => `atom-text-editor,atom-text-editor`

* `atom-text-editor .wrap-guide,
:host .wrap-guide` => `atom-text-editor .wrap-guide,atom-text-editor .wrap-guide`

* `atom-text-editor .indent-guide,
:host .indent-guide` => `atom-text-editor .indent-guide,atom-text-editor .indent-guide`

* `atom-text-editor .invisible-character,
:host .invisible-character` => `atom-text-editor .invisible-character,atom-text-editor .invisible-character`

* `atom-text-editor .gutter,
:host .gutter` => `atom-text-editor .gutter,atom-text-editor .gutter`

* `atom-text-editor .gutter .icon-right,
:host .gutter .icon-right` => `atom-text-editor .gutter .icon-right,atom-text-editor .gutter .icon-right`

* `atom-text-editor .gutter .line-number.cursor-line,
:host .gutter .line-number.cursor-line` => `atom-text-editor .gutter .line-number.cursor-line,atom-text-editor .gutter .line-number.cursor-line`

* `atom-text-editor .gutter .line-number.cursor-line .icon-right,
:host .gutter .line-number.cursor-line .icon-right` => `atom-text-editor .gutter .line-number.cursor-line .icon-right,atom-text-editor .gutter .line-number.cursor-line .icon-right`

* `atom-text-editor .gutter .line-number.cursor-line-no-selection,
:host .gutter .line-number.cursor-line-no-selection` => `atom-text-editor .gutter .line-number.cursor-line-no-selection,atom-text-editor .gutter .line-number.cursor-line-no-selection`

* `atom-text-editor .gutter .line-number.git-line-added,
:host .gutter .line-number.git-line-added` => `atom-text-editor .gutter .line-number.git-line-added,atom-text-editor .gutter .line-number.git-line-added`

* `atom-text-editor .gutter .line-number.git-line-modified,
:host .gutter .line-number.git-line-modified` => `atom-text-editor .gutter .line-number.git-line-modified,atom-text-editor .gutter .line-number.git-line-modified`

* `atom-text-editor .gutter .line-number.git-line-removed:before,
:host .gutter .line-number.git-line-removed:before` => `atom-text-editor .gutter .line-number.git-line-removed:before,atom-text-editor .gutter .line-number.git-line-removed:before`

* `atom-text-editor .gutter .line-number.folded,
:host .gutter .line-number.folded,
atom-text-editor .gutter .line-number:after,
:host .gutter .line-number:after,
atom-text-editor .fold-marker:after,
:host .fold-marker:after` => `atom-text-editor .gutter .line-number.folded,atom-text-editor .gutter .line-number.folded,
atom-text-editor .gutter .line-number:after,atom-text-editor .gutter .line-number:after,
atom-text-editor .fold-marker:after,atom-text-editor .fold-marker:after`

* `atom-text-editor .invisible,
:host .invisible` => `atom-text-editor .invisible,atom-text-editor .invisible`

* `atom-text-editor .cursor,
:host .cursor` => `atom-text-editor .cursor,atom-text-editor .cursor`

* `atom-text-editor .selection .region,
:host .selection .region` => `atom-text-editor .selection .region,atom-text-editor .selection .region`

* `atom-text-editor .selection .region,
:host .selection .region` => `atom-text-editor .selection .region,atom-text-editor .selection .region`

* `:host .find-result .region,
atom-text-editor .find-result .re

**Comment by puranjayjain** [comment]
Thank you for your report I'll be upgrading all my packages to atom 1.x from 0.x branches in the near future. It would be more helpful if you could send a Pull Request too!

**Comment by puranjayjain** [comment]
@Slaiyer fixed in the PR #3
